# Generated by Django 3.1.5 on 2021-02-02 09:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=100)),
                ('road_code', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('prov_code', models.IntegerField()),
                ('prov_name_1', models.CharField(max_length=200)),
                ('prov_name_2', models.CharField(max_length=200)),
                ('district_code', models.CharField(max_length=200)),
                ('district_name', models.CharField(max_length=200)),
                ('district_1', models.CharField(max_length=200)),
                ('IDO_name', models.CharField(max_length=200)),
                ('length_km', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
