# Generated by Django 3.1.5 on 2021-01-29 05:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='location',
        ),
        migrations.AddField(
            model_name='road',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
