# Generated by Django 3.1.5 on 2021-02-02 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0002_auto_20210202_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
    ]
