# Generated by Django 3.1.5 on 2021-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0008_auto_20210203_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='roads',
            name='road_code',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roads',
            name='section_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
