# Generated by Django 3.1.5 on 2021-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0011_auto_20210203_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='section_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
