# Generated by Django 3.1.5 on 2021-02-04 11:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0012_auto_20210204_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
